# Last edited: 2025-10-18
name: Keep Supabase Alive

on:
  schedule:
    # Every 3 days at midnight UTC
    - cron: "0 0 */3 * *"
  workflow_dispatch: # allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "Pinging Supabase endpoint..."
          curl -s -H "apikey: $SUPABASE_KEY" "$SUPABASE_URL/rest/v1/" > /dev/null
          echo " Supabase ping completed successfully."
